<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.16.3 by Michael Rose
  Copyright 2013-2019 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Exception handling particulars in C# - Wayne’s Geek Life</title>
<meta name="description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="Wayne's Geek Life">
<meta property="og:title" content="Exception handling particulars in C#">
<meta property="og:url" content="https://wayneye.me/Exception-Handling-Particulars-In-Csharp">


  <meta property="og:description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:">





  <meta name="twitter:site" content="@wayneye">
  <meta name="twitter:title" content="Exception handling particulars in C#">
  <meta name="twitter:description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:">
  <meta name="twitter:url" content="https://wayneye.me/Exception-Handling-Particulars-In-Csharp">

  
    <meta name="twitter:card" content="summary">
    
  

  



  <meta property="article:published_time" content="2011-07-08T00:00:00-07:00">






<link rel="canonical" href="https://wayneye.me/Exception-Handling-Particulars-In-Csharp">













<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="Wayne's Geek Life Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">

<!--[if IE ]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->
<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon/favicon-16x16.png">
<link rel="manifest" href="/assets/images/favicon/site.webmanifest">
<link rel="mask-icon" href="/assets/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

<!-- end custom head snippets -->

  </head>

  <body class="layout--single wide">

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
        <a class="site-title" href="/">Wayne's Geek Life</a>
        <ul class="visible-links">
<li class="masthead__menu-item">
              <a href="/categories/">Categories</a>
            </li>
<li class="masthead__menu-item">
              <a href="/tags/">Tags</a>
            </li>
<li class="masthead__menu-item">
              <a href="/search/">Search</a>
            </li>
<li class="masthead__menu-item">
              <a href="/gallery/">Gallery</a>
            </li>
<li class="masthead__menu-item">
              <a href="/vlog/">Vlog</a>
            </li>
<li class="masthead__menu-item">
              <a href="/about/">About</a>
            </li>
</ul>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  


<div itemscope itemtype="https://schema.org/Person">

  
    <div class="author__avatar">
      

      
        <img src="/assets/images/me.jpg" alt="Wayne Ye" itemprop="image">
      
    </div>
  

  <div class="author__content">
    
      <h3 class="author__name" itemprop="name">Wayne Ye</h3>
    
    
      <p class="author__bio" itemprop="description">
        Whatever is worth doing is worth doing well!
      </p>
    
  </div>

  <div class="author__urls-wrapper">
    <button class="btn btn--inverse">Follow</button>
    <ul class="author__urls social-icons">
      
        <li itemprop="homeLocation" itemscope itemtype="https://schema.org/Place">
          <i class="fas fa-fw fa-map-marker-alt" aria-hidden="true"></i> <span itemprop="name">San Francisco</span>
        </li>
      

      
        
          
            <li><a href="mailto:hi@wayneye.me" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
          
        
          
            <li><a href="https://wayneye.me" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-link" aria-hidden="true"></i> Website</a></li>
          
        
          
            <li><a href="https://www.linkedin.com/in/wayneye" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i> LinkedIn</a></li>
          
        
          
            <li><a href="https://github.com/WayneYe/" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub</a></li>
          
        
          
            <li><a href="https://twitter.com/wayneye" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i> Twitter</a></li>
          
        
      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      <!--
  <li>
    <a href="http://link-to-whatever-social-network.com/user/" itemprop="sameAs" rel="nofollow noopener noreferrer">
      <i class="fas fa-fw" aria-hidden="true"></i> Custom Social Profile Link
    </a>
  </li>
-->
    </ul>
  </div>
</div>

  
  </div>


  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Exception handling particulars in C#">
    <meta itemprop="description" content='BackgroundException handling appears in most .NET applications, this post is trying to describe some  Exception handling particulars in C# which might not take enough awareness from C# developers. Differences between throw and throw ex I guess every C# developer has seen code snippet below: try {     // Do some work, exception occurs } catch (IOException ex) {     // Exception caught, re-throw it to bubble up     throw ex; }In the catch block, we can rethrow the caught exception instance of IOException to higher level, and we may also saw another way in a little different: try {     // Do some work, exception occurs } catch (IOException ex) {     // Exception caught, re-throw it to bubble up     throw; }Is there any different? The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception {     public DummyException(String dummymsg)         : base(dummymsg)     {      }      public DummyException(String dummymsg, Exception innerException)         : base(dummymsg, innerException)     {      } } And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program {     private static void DoLowLevelOperation()     {         // Do some low level operation         throw new DummyException("A dummy exception message!");     }      public static void MethodThrowException1()     {         try         {             DoLowLevelOperation();         }         catch (DummyException de)         {             throw;         }     }     public static void MethodThrowException2()     {         try         {             DoLowLevelOperation();         }         catch (DummyException de)         {             throw de;         }     }      static void Main(string[] args)     {         try         {             MethodThrowException1();         }         catch (DummyException de1)         {             Console.WriteLine(de1.Message);             Console.WriteLine(de1.StackTrace);         }          try         {             MethodThrowException2();         }         catch (DummyException de2)         {             Console.WriteLine(de2.Message);             Console.WriteLine(de2.StackTrace);         }     } } The result will be:'>
    <meta itemprop="datePublished" content="July 08, 2011">
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Exception handling particulars in C#
</h1>
          
        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right ">
            <nav class="toc">
              <header><h4 class="nav__title">
<i class="fas fa-cog"></i> On this page</h4></header>
              <ul class="toc__menu">
  <li><a href="#">Background</a></li>
  <li><a href="#">Differences between throw and throw ex </a></li>
  <li><a href="#">Is there any different? </a></li>
  <li><a href="#">Different between parameterless catch and catch (Exception ex) </a></li>
  <li><a href="#">Further reading  </a></li>
</ul>
            </nav>
          </aside>
        
        <h3>Background</h3>
<p>Exception handling appears in most .NET applications, this post is trying to describe some  Exception handling particulars in C# which might not take enough awareness from C# developers. </p>
<h3>Differences between throw and throw ex </h3>
<p>I guess every C# developer has seen code snippet below:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #7f9f7f;">// Do some work, exception occurs</span><br> <span style="color: #dcdccc;">}</span><br> <span style="color: #e3ceab;">catch</span> (IO<span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">ex</span>)<br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #7f9f7f;">// Exception caught, re-throw it to bubble up</span><br>     <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">ex</span>;<br> <span style="color: #dcdccc;">}</span></pre>
<p>In the <code>catch</code> block, we can rethrow the caught exception instance of <code>IOException </code>to higher level, and we may also saw another way in a little different:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #7f9f7f;">// Do some work, exception occurs</span><br> <span style="color: #dcdccc;">}</span><br> <span style="color: #e3ceab;">catch</span> (IO<span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">ex</span>)<br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #7f9f7f;">// Exception caught, re-throw it to bubble up</span><br>     <span style="color: #e3ceab;">throw</span>;<br> <span style="color: #dcdccc;">}</span></pre>
<h3><strong>Is there any different? </strong></h3>
<p>The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException.</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">internal</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">Exception</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #e3ceab;">public</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #dcdccc;">String</span> <span style="color: #dcdccc;">dummymsg</span>)<br>         <span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">base</span>(<span style="color: #dcdccc;">dummymsg</span>)<br>     <span style="color: #dcdccc;">{</span><br> <br>     <span style="color: #dcdccc;">}</span><br> <br>     <span style="color: #e3ceab;">public</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #dcdccc;">String</span> <span style="color: #dcdccc;">dummymsg</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">innerException</span>)<br>         <span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">base</span>(<span style="color: #dcdccc;">dummymsg</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">innerException</span>)<br>     <span style="color: #dcdccc;">{</span><br> <br>     <span style="color: #dcdccc;">}</span><br> <span style="color: #dcdccc;">}</span></pre>
<p> And then I manually throw the DummyException within one method, while handle it in different way mentioned above:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">Program</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #e3ceab;">private</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">DoLowLevelOperation</span>()<br>     <span style="color: #dcdccc;">{</span><br>         <span style="color: #7f9f7f;">// Do some low level operation</span><br>         <span style="color: #e3ceab;">throw</span> <span style="color: #e3ceab;">new</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #cc9393;">"A dummy exception message!"</span>);<br>     <span style="color: #dcdccc;">}</span><br> <br>     <span style="color: #e3ceab;">public</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">MethodThrowException1</span>()<br>     <span style="color: #dcdccc;">{</span><br>         <span style="color: #e3ceab;">try</span><br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">DoLowLevelOperation</span>();<br>         <span style="color: #dcdccc;">}</span><br>         <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #e3ceab;">throw</span>;<br>         <span style="color: #dcdccc;">}</span><br>     <span style="color: #dcdccc;">}</span><br>     <span style="color: #e3ceab;">public</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">MethodThrowException2</span>()<br>     <span style="color: #dcdccc;">{</span><br>         <span style="color: #e3ceab;">try</span><br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">DoLowLevelOperation</span>();<br>         <span style="color: #dcdccc;">}</span><br>         <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">de</span>;<br>         <span style="color: #dcdccc;">}</span><br>     <span style="color: #dcdccc;">}</span><br> <br>     <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">Main</span>(<span style="color: #dfdfbf; font-weight: bold;">string</span><span style="color: #dcdccc;">[]</span> <span style="color: #dcdccc;">args</span>)<br>     <span style="color: #dcdccc;">{</span><br>         <span style="color: #e3ceab;">try</span><br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">MethodThrowException1</span>();<br>         <span style="color: #dcdccc;">}</span><br>         <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de1</span>)<br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de1</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Message</span>);<br>             <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de1</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">StackTrace</span>);<br>         <span style="color: #dcdccc;">}</span><br> <br>         <span style="color: #e3ceab;">try</span><br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">MethodThrowException2</span>();<br>         <span style="color: #dcdccc;">}</span><br>         <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de2</span>)<br>         <span style="color: #dcdccc;">{</span><br>             <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de2</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Message</span>);<br>             <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de2</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">StackTrace</span>);<br>         <span style="color: #dcdccc;">}</span><br>     <span style="color: #dcdccc;">}</span><br> <span style="color: #dcdccc;">}</span></pre>
<p> The result will be:</p>
<p><!--more--></p>
<p><img title="Exception handling" src="https://byfiles.storage.live.com/y1pOsmopqaR3U4_pOpoKta9ao4On0IrEWZf78M-fGOIROnhl0nPaFzDEJSeykT3-jL8fBn5YBddITP0rM9qzZU3qg/EXHandling.png?psid=1" alt="Exception handling" width="677" height="442"></p>
<p>So the difference is, "throw ex" will truncate the StackTrace information where it was originally thrown (this will cause the so called issue - "breaking the stack"), but "throw" will contain all the information.</p>
<p>Delve deeper, "throw ex" in IL level essentially indicates "<strong>rethrow</strong>", whereas "throw" indicate "<strong>throw</strong>", please see their IL code below:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">method</span> <span style="color: #e3ceab;">public</span> <span style="color: #dcdccc;">hidebysig</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">MethodThrowException1</span>() <span style="color: #dcdccc;">cil</span> <span style="color: #dcdccc;">managed</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">maxstack</span> <span style="color: #8cd0d3;">1</span><br>     <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">locals</span> <span style="color: #dcdccc;">init</span> (<br> <span style="color: #efef8f;">        [0]</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br>     <span style="color: #dcdccc;">L_0000</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0001</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0002</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">call</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Program</span><span style="color: #dcdccc;">::</span><span style="color: #dcdccc;">DoLowLevelOperation</span>()<br>     <span style="color: #dcdccc;">L_0007</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0008</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0009</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">leave</span><span style="color: #dcdccc;">.</span>s <span style="color: #dcdccc;">L_000f</span><br>     <span style="color: #dcdccc;">L_000b</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">stloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br>     <span style="color: #dcdccc;">L_000c</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_000d</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">rethrow</span> <br>     <span style="color: #dcdccc;">L_000f</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0010</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ret</span> <br>     <span style="color: #dcdccc;">.</span><span style="color: #e3ceab;">try</span> <span style="color: #dcdccc;">L_0001</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #e3ceab;">catch</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">handler</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000f</span><br> <span style="color: #dcdccc;">}</span></pre>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">method</span> <span style="color: #e3ceab;">public</span> <span style="color: #dcdccc;">hidebysig</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">MethodThrowException2</span>() <span style="color: #dcdccc;">cil</span> <span style="color: #dcdccc;">managed</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">maxstack</span> <span style="color: #8cd0d3;">1</span><br>     <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">locals</span> <span style="color: #dcdccc;">init</span> (<br> <span style="color: #efef8f;">        [0]</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br>     <span style="color: #dcdccc;">L_0000</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0001</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0002</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">call</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Program</span><span style="color: #dcdccc;">::</span><span style="color: #dcdccc;">DoLowLevelOperation</span>()<br>     <span style="color: #dcdccc;">L_0007</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0008</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0009</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">leave</span><span style="color: #dcdccc;">.</span>s <span style="color: #dcdccc;">L_000f</span><br>     <span style="color: #dcdccc;">L_000b</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">stloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br>     <span style="color: #dcdccc;">L_000c</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_000d</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ldloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br>     <span style="color: #dcdccc;">L_000e</span><span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">throw</span> <br>     <span style="color: #dcdccc;">L_000f</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br>     <span style="color: #dcdccc;">L_0010</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ret</span> <br>     <span style="color: #dcdccc;">.</span><span style="color: #e3ceab;">try</span> <span style="color: #dcdccc;">L_0001</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #e3ceab;">catch</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">handler</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000f</span><br> <span style="color: #dcdccc;">}</span></pre>
<p> The definition for "rethrow" and "throw" in IL are showing below:</p>
<blockquote>
<p>rethrow: <strong>Rethrows the current exception.</strong></p>
<p>throw: <strong>Throws the exception Object currently on evaluation stack.</strong></p>
</blockquote>
<p><strong><strong>So what should we do?</strong></strong></p>
<p>Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #e3ceab;">throw</span> <span style="color: #e3ceab;">new</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #cc9393;">"A dummy exception message!"</span>);<br> <span style="color: #dcdccc;">}</span><br> <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br> <span style="color: #dcdccc;">{</span><br>     <span style="color: #dcdccc;">AnotherTypeOfException</span> <span style="color: #dcdccc;">anotherTypeOfException</span> <span style="color: #dcdccc;">=</span> <span style="color: #e3ceab;">new</span> <span style="color: #dcdccc;">AnotherTypeOfException</span>(<span style="color: #cc9393;">"Customized exception message."</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">de</span>)<br>     <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">anotherTypeOfException</span>;<br> <span style="color: #dcdccc;">}</span></pre>
<p>When initializes <code>AnotherTypeOfException</code> we actually calls Exception's construcor "<code>(String message, Exception innerException)</code>", so finally there will be <strong>no information loss.</strong></p>
<p>There is one particular details, when we wrote code similar with below, Resharper will warning us it is redundant, because "<em>The catch statement may appear to be doing something, but it really isn't: all it's doing is throwing the exception (with the same stack information)</em>", <a href="http://confluence.jetbrains.net/display/ReSharper/Catch+clause+is+redundant" target="_blank">Resharper link</a>. </p>
<p><img src="http://www.codeproject.com/KB/Blogs/228868/RedundantThrow1.png" alt="RedundantThrow1.png" width="303" height="137"></p>
<p><img src="http://www.codeproject.com/KB/Blogs/228868/RedundantThrow2.png" alt="RedundantThrow2.png" width="389" height="203">  </p>
<p>Instead, if we wrote "<code>throw de</code>", in the above example, Resharper will NOT give you any warning, because now we know they are different, "<code>throw de</code>" will <strong>truncate the StackTrace information and rethrow the <code>DemmyException </code>instance</strong>. </p>
<h3>Different between parameterless catch and catch (Exception ex) </h3>
<p>Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from <code>System.Exception</code>, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those Non-CLS-Compliant exceptions into an specific Exception type: <a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.runtimewrappedexception.aspx" target="_blank">RuntimeWrappedException</a>, it has a property: <code>WrappedException</code><code> </code>to store a non-CLS-Compliant exception, results in statement "<code>catch (Exception ex)</code>" can catch all runtime exceptions.</p>
<p>Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying <a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.runtimecompatibilityattribute.aspx" target="_blank">RuntimeCompatibility </a>attribute to your assembly, i.e. AssemblyInfo.cs.</p>
<pre>[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]
</pre>
<p>By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to <code>System.Exception</code>, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.  </p>
<h3>Further reading  </h3>
<p>Exception Handling on MSDN<br><a href="http://msdn.microsoft.com/en-us/library/ms229005.aspx">http://msdn.microsoft.com/en-us/library/ms229005.aspx</a></p>
<p>Using COM Object<br><a href="http://insideaspnet.com/index/using-com-objects/">http://insideaspnet.com/index/using-com-objects/</a> </p>
<p>Difference between "throw" and "throw ex" in .NET<br><a href="http://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspx">http://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspx</a></p>
<p>Also posted at my blog - Wayne's Geek Life: <br><a href="http://wayneye.com/Blog/Different-Between-Throw-Throw-EX">http://wayneye.com/Blog/Different-Between-Throw-Throw-EX </a> </p>
<p>Also posted on CodeProject: <a href="http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex</a></p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#hack" class="page__taxonomy-item" rel="tag">Hack</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#hack" class="page__taxonomy-item" rel="tag">Hack</a>
    
    </span>
  </p>


        
          <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2011-07-08T00:00:00-07:00">July 08, 2011</time></p>
        
      </footer>

      <section class="page__share">
  <!---->
    <!--<h4 class="page__share-title">Share on</h4>-->
  <!---->

  <!--<a href="https://twitter.com/intent/tweet?via=wayneye&text=Exception+handling+particulars+in+C%23%20https%3A%2F%2Fwayneye.me%2FException-Handling-Particulars-In-Csharp" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>-->

  <!--<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwayneye.me%2FException-Handling-Particulars-In-Csharp" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>-->

  <!--<a href="https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fwayneye.me%2FException-Handling-Particulars-In-Csharp" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>-->

  
  <figure style="margin-top: 10px; width: 380px;">
      <a href="/assets/images/dashang.jpg"><img src="/assets/images/dashang.jpg" alt="微信打赏"></a>
  </figure>
</section>


      
  <nav class="pagination">
    
      <a href="/HTML5-Web-Socket-In-Essence" class="pagination--pager" title="HTML5 Web Socket in Essence
">Previous</a>
    
    
      <a href="/JavaScript-Foundation-Of-The-Language" class="pagination--pager" title="JavaScript - Foundation of the Language
">Next</a>
    
  </nav>

    </div>

    
      <div class="page__comments">
  
  
      <h4 class="page__comments-title">Leave a comment</h4>
      <section id="disqus_thread"></section>
    
</div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You may also enjoy</h4>
      <div class="grid__wrapper">
        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/BMW-Convertible-As-My-Beater-Car" rel="permalink">BMW Convertible As My Beater Car
</a>
      
    </h2>
    
    <p class="archive__item-excerpt" itemprop="description">
  Life is too short to drive boring cars





I bought a 2015 BMW X5 Dec last year, it has been half a year so far (with 2 months she stayed inside the garage for most of the time due to the pandemic), I am pretty satisfied with it, her condition is absolutely excellent, everything works, yes you see it correctly, after 5 years of its life, there was nothing broken, as BMW vehicle built in recent years, this is something not VERY easy.  My plan is to keep it as long as possible before it turns into an endless money pit, and keeping her value as high as possible, one of the major reason I b...</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/2019-12-07-SkyJump-Las-Vegas" rel="permalink">SkyJump from Stratosphere Tower at Las Vegas - Smile all the way down
</a>
      
    </h2>
    
    <p class="archive__item-excerpt" itemprop="description">Instead of spending any cent in the money pit casinos, I’d chose to do something more meaningful and exciting :)


    
    
    
    SkyJump Las Vegas




  SkyJump Las Vegas holds the Guinness World Record for highest commercial decelerator descent with an official height of 829 ft (253 m) and is located at Stratosphere Las Vegas. As part of its grand opening event, Las Vegas Mayor Oscar Goodman presented a written proclamation deeming April 20, 2010 as SkyJump Day in Las Vegas.
  – Wikipedia (https://en.wikipedia.org/wiki/SkyJump_Las_Vegas)





  



</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/AWS-reinvent-Las-Vegas" rel="permalink">AWS reinvent 2019 - Las Vegas
</a>
      
    </h2>
    
    <p class="archive__item-excerpt" itemprop="description">This is my second time attending AWS re-Invent, last time was year 2017, the purpose of this blog is to summarize what I’ve learned, impressed and entertained <img class="emoji" title=":smile:" alt=":smile:" src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png" height="20" width="20">


    
    At reinvent logo



    
    Crazy crowd at midnight madness party


Overall during my week staying my daily schedule was listening to sessions mixed with slack/emails during the daylight, and party/social in the evening time.

All the keynotes/sessions have been uploaded here:  https://reinvent.awsevents.com/learn/keynotes/  and all announcements were summarized at this page, my personal top 5 thrilled announcement...</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/Ireland-Trip-2019" rel="permalink">Ireland Trip 2019
</a>
      
    </h2>
    
    <p class="archive__item-excerpt" itemprop="description">
  WHEN YOU ARE OLD



  When you are old and grey and full of sleep, 
And nodding by the fire, take down this book, 
And slowly read, and dream of the soft look 
Your eyes had once, and of their shadows deep; 
How many loved your moments of glad grace, 
And loved your beauty with love false or true, 
But one man loved the pilgrim soul in you, 
And loved the sorrows of your changing face; 
And bending down beside the glowing bars, 
Murmur, a little sadly, how Love fled 
And paced upon the mountains overhead 
And hid his face amid a crowd of stars. 
– By William Butler Yeats



  当你年老时 
　　 　...</p>
  </article>
</div>

        
      </div>
    </div>
  
  
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4ea2897777c94202"></script>

    </div>

    

    <div class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    
      <li><strong>Follow:</strong></li>
    

    
      
        
          <li><a href="mailto:hi@wayneye.me" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
        
          <li><a href="https://wayneye.me" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-link" aria-hidden="true"></i> Website</a></li>
        
      
        
          <li><a href="https://twitter.com/wayneye" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i> Twitter</a></li>
        
      
        
          <li><a href="https://facebook.com/WayneYeDotCom" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
          <li><a href="https://github.com/WayneYe/" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">© 2023 Wayne Ye. All rights reserved.
 
  <!--Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>.</div>-->

      
    </div>

    
  <script src="/assets/js/main.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>







    
  <script>
    var disqus_config = function () {
      this.page.url = "https://wayneye.me/Exception-Handling-Particulars-In-Csharp";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "/Exception-handling-particulars-in-C#"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://wayneye.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>


  





  </footer>
</div></body>
</html>
